### ISSUE TITLE
Setting item by TKey fails to sync internalList

### ISSUE THREAD

**Issue by johnnysbug** [johndkane/GenericOrderedDictionary#1]
It appears the indexer this[TKey] fails to synchronize the internal list if the internal dictionary contains the key.

**Comment by johndkane** [comment]
Summary; Added new test ReplaceItem_ByKey() in commit eae8deb502b459c67b118419beb3c14bd2465323  to reproduce issue described for indexer this[TKey]
Fixed issue in commit 7beb17f8f21776b5040172c23a87f7959fb173cf
Also upgrade NUnit package, added VS adapter/runner, and saved solution with VS 2017 marker.
